# Generated by Django 2.2.5 on 2020-01-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myhit',
            name='hit',
        ),
    ]
