# Generated by Django 2.2.5 on 2020-01-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_myhit_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhit',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
