# Generated by Django 2.2.5 on 2020-01-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200119_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myhit',
            old_name='writer',
            new_name='hitter',
        ),
    ]
