# Generated by Django 2.2.5 on 2020-01-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200119_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhit',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
