# Generated by Django 2.2.5 on 2020-01-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_letter_bgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='bgm',
            field=models.URLField(),
        ),
    ]
