# Generated by Django 2.2.5 on 2020-01-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200120_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emogi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smile', models.PositiveIntegerField(default=0)),
                ('panic', models.PositiveIntegerField(default=0)),
                ('happy', models.PositiveIntegerField(default=0)),
                ('sad', models.PositiveIntegerField(default=0)),
                ('funny', models.PositiveIntegerField(default=0)),
                ('angry', models.PositiveIntegerField(default=0)),
                ('embarass', models.PositiveIntegerField(default=0)),
                ('love', models.PositiveIntegerField(default=0)),
                ('letter', models.ManyToManyField(to='myapp.Letter')),
            ],
        ),
    ]
