# Generated by Django 2.2.9 on 2020-01-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200120_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='bgm',
        ),
    ]
