# Generated by Django 2.2.5 on 2020-01-20 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_mywrite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='bgm',
        ),
    ]
